events { 
    worker_connections 1024; 
}

http {
    # Em vez de IPs fixos, usamos o DNS do Docker.
    # Quando escalamos o serviço "app", o Docker resolve esse nome 
    # em Round-Robin para todos os containers PHP rodando.
    upstream php_servers {
        server app:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://php_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

events { }
